name: main.yml

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main

permissions:
  issues: write
  contents: write

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Navigate to project directory
      run: cd 14E-TP2-A2024

    - name: Restore dependencies
      run: dotnet restore 14E-TP2-A2024/Automate.csproj

    - name: Build project
      run: dotnet build --configuration Release --no-restore 14E-TP2-A2024/Automate.csproj

    - name: Run tests
      id: test
      run: dotnet test --no-build --verbosity normal 14E-TP2-A2024/Automate.csproj

    - name: Create GitHub issue on test failure
      if: failure()
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.TOKEN }}
        script: |
          const { owner, repo } = context.repo;
          const issueTitle = `Test Failure in ${context.workflow}`;
          const issueBody = `One or more tests failed in the workflow **${context.workflow}**. Please check the details and fix the issues.`;
          const issue = await github.rest.issues.create({
            owner,
            repo,
            title: issueTitle,
            body: issueBody,
            labels: ['bug', 'test-failure']
          });
          core.setOutput('issue-url', issue.data.html_url);

  release:
    needs: build-and-test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main') || contains(github.event.head_commit.message, 'TP3-V')
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract short SHA
      id: extract_short_sha
      run: |
        $shortSha = $env:GITHUB_SHA.Substring(0, 7)
        echo "SHORT_SHA=$shortSha" >> $GITHUB_ENV
        echo "::set-output name=short_sha::$shortSha"

    - name: Print SHORT_SHA
      run: echo "SHORT_SHA:${{ steps.extract_short_sha.outputs.short_sha }}"

    - name: Publish project
      run: dotnet publish --configuration Release --output ./publish 14E-TP2-A2024/Automate.csproj

    - name: List published files
      run: dir ./14E-TP2-A2024/bin/Release/net6.0-windows

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: TP3-V${{ steps.extract_short_sha.outputs.short_sha }}
        release_name: TP3-V${{ steps.extract_short_sha.outputs.short_sha }}
        body: |
          ## Nouvelle version
          - Nouvelle remise
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./14E-TP2-A2024/bin/Release/net6.0-windows/Automate.exe
        asset_name: Automate.exe
        asset_content_type: application/octet-stream