name: main.yml

on:
  push:
    branches:
      - '*'  
  pull_request:
    branches:
      - main

permissions:
  issues: write

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Navigate to project directory
      run: cd 14E-TP2-A2024

    - name: Restore dependencies
      run: dotnet restore 14E-TP2-A2024/Automate.csproj

    - name: Build project
      run: dotnet build --configuration Release --no-restore 14E-TP2-A2024/Automate.csproj

    - name: Run tests
      id: test
      run: dotnet test --no-build --verbosity normal 14E-TP2-A2024/Automate.csproj

    - name: Create GitHub issue on test failure
      if: failure()
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.TOKEN }}
        script: |
          const { owner, repo } = context.repo;
          const issueTitle = `Test Failure in ${context.workflow}`;
          const issueBody = `One or more tests failed in the workflow **${context.workflow}**. Please check the details and fix the issues.`;
          const issue = await github.rest.issues.create({
            owner,
            repo,
            title: issueTitle,
            body: issueBody,
            labels: ['bug', 'test-failure']
          });
          core.setOutput('issue-url', issue.data.html_url);

  release:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: TP3-V* 
        release_name: 'Release v1.0.0'
        body: |
          ## Nouvelle version disponible
          - Remise du TP3
        draft: false
        prerelease: false
